---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/profile.yaml
  label: Profile
- type: document
  path: data/appearance.yaml
  label: Appearance
- type: document
  path: content/about/_index.md
  label: About
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: document
  path: data/featured.yml
  label: Featured
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: document
  path: content/gallery/_index.md
  label: Gallery
- type: document
  path: content/menu/_index.md
  label: Menu
- type: directory
  path: content/legal
  label: Legal
  create: all
  match: "**/*"
upload_dir: brian-vu/phohaplusdiamondbar
public_path: https://res.cloudinary.com/hungryram19/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
